name: 'build'

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [manual-build]
  schedule:
    - cron: '0 0/4 * * *'

env:
  CI: true
  PY_COLORS: 1

jobs:

  build:
    runs-on: windows-latest
    continue-on-error: true
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: base-devel msys2-devel mingw-w64-x86_64-toolchain mingw-w64-i686-toolchain git python-pip python winpty

    - name: Check install
      run: |
        pacman -Qkq

    - name: Install deps
      run: |
        python -m pip install --user -r requirements.txt

    - name: Show build queue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python autobuild.py show

    - name: Clean up assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python autobuild.py clean-assets

    - name: Process build queue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export PACKAGER="CI (msys2-devtools/${GITHUB_SHA::8}/${GITHUB_RUN_ID})"
        python autobuild.py build "$(cygpath -u "$(powershell -c '(get-location).Drive.Root')/_")"